### PR TITLE
implement ecto::BREAK behavior

### PR DESCRIPTION
**Pull request by v4hn**
This patch makes ecto schedule the next iteration through the plasm with
ecto::BREAK as discussed in https://github.com/plasmodic/ecto/issues/251

### CODE REVIEW

**Comment by stonier** [comment]
@v4hn this looks good...and rather simple! :neckbeard:

Would you care to add a python test for this so we can make sure it doesn't break in the future? I think all you'd need to do would be to create a cell that utilises `ecto::BREAK` [here](https://github.com/plasmodic/ecto/tree/master/test/cells) and a sensible test of some sort [here](https://github.com/plasmodic/ecto/tree/master/test/scripts). These are actually simpler than they look to add and can be run directly.

I am just checking the docs and it looks like there is no snippet on the return values from ecto cells. If you get this in, I'll add something there covering each of `ecto::QUIT`, `ecto::OK`, `ecto::DO_OVER` and `ecto::BREAK`.

**Comment by v4hn** [comment]
Yeah, given how overly complex ecto is, it's refreshing
to see easy to understand functionality, isn't it? :D

I just added an appropriate test.

**Comment by vrabaud** [comment]
it all looks good to me. Thx !

**Comment by v4hn** [comment]
Thanks @vrabaud 
Do I get you to release this into indigo? :)
(probably together with @stonier's doc changes...

**Comment by vrabaud** [comment]
yes, very soon: the doc changes have to be reviewed (@v4hn, please go ahead) and the PR about ARM linkage too.

**Comment by v4hn** [comment]
@vrabaud: done, I reviewed all open requests :sunglasses:

**Pull request merged**
